#ifndef __EEPROMCONFIG_H
#define __EEPROMCONFIG_H


//#define   _EEPROM_F1_LOW_DESTINY
#define   _EEPROM_F1_MEDIUM_DESTINY
//#define   _EEPROM_F1_HIGH_DESTINY

#define		_EEPROM_USE_FLASH_PAGE				127

#endif
